FROM php:7.4-fpm-alpine

RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/5.3.1.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-* /usr/src/php/ext/redis \
    && apk add --update --no-cache gmp gmp-dev imagemagick imagemagick-dev $PHPIZE_DEPS \
    && docker-php-ext-install gmp redis pdo_mysql opcache pcntl \
    && pecl install imagick \
    && docker-php-ext-enable imagick

WORKDIR /var/www/html

#RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY build/php/php.ini "$PHP_INI_DIR/php.ini"
COPY build/php/conf.d/opcache.ini /usr/local/etc/php/conf.d/
COPY build/php/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY build/supervisor/ /etc/supervisor/conf.d/

RUN chmod +x /etc/supervisor/conf.d/laravel-horizon.conf
CMD ["php", "artisan", "horizon"]